# Generated by Django 4.2.11 on 2024-03-30 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-id"]},
        ),
    ]
